<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <link rel="shortcut icon" href="<?= $this->url->get('assets/images/favicon.ico') ?>">


    <title>LPPM Automation</title>

    <!-- App css -->
    <link href="<?= $this->url->getStatic('assets/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->getStatic('assets/css/icons.css') ?>" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->getStatic('assets/css/style.css') ?>" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->getStatic('assets/css/core.css') ?>" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->getStatic('assets/css/components.css') ?>" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->getStatic('assets/css/pages.css') ?>" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->getStatic('assets/css/menu.css') ?>" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->getStatic('assets/css/responsive.css') ?>" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->getStatic('assets/css/typicons.css') ?>" rel="stylesheet" type="text/css"/>

    <script src="<?= $this->url->get('assets/js/modernizr.min.js') ?>"></script>



</head>
<body class="fixed-left">


            <?= $this->getContent() ?>



    </div>

    <!-- jQuery  -->
        <script src="<?= $this->url->get("assets/js/jquery.min.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/popper.min.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/bootstrap.min.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/detect.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/fastclick.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/jquery.blockUI.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/waves.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/jquery.nicescroll.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/jquery.slimscroll.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/jquery.scrollTo.min.js")?>"></script>

        <!-- App js -->
        <script src="<?= $this->url->get("assets/js/jquery.core.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/jquery.app.js")?>"></script>
    </body>
</html>
