<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
        <meta name="author" content="Coderthemes">

		<link rel="shortcut icon" href="<?= $this->url->get('assets/images/favicon.ico') ?>">
        

        <title>Office Automation</title>

        <link rel="stylesheet"  href="<?= $this->url->get('assets/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet"  href="<?= $this->url->get('assets/css/core.css') ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet"  href="<?= $this->url->get('assets/css/components.css') ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet"  href="<?= $this->url->get('assets/css/icons.css') ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet"  href="<?= $this->url->get('assets/css/pages.css') ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet"  href="<?= $this->url->get('assets/css/menu.css') ?>" rel="stylesheet" type="text/css"/>
        <link rel="stylesheet"  href="<?= $this->url->get('assets/css/responsive.css') ?>" rel="stylesheet" type="text/css"/>

        <script src="<?= $this->url->get('assets/js/modernizr.min.js') ?>"></script>
        <script src="<?= $this->url->get('assets/plugins/moment/moment.js') ?>"></script>

    </head>

    <?php if ($this->session->get('nip')): ?>

    <body class="fixed-left">

        <!-- Begin page -->
        <div id="wrapper">

            <!-- Top Bar Start -->
            <div class="topbar">

                <!-- LOGO -->
                <div class="topbar-left">
                    <a href="index.html" class="logo"><span>Office<span> Automation</span></span><i class="mdi mdi-layers"></i></a>
                </div>

                <!-- Button mobile view to collapse sidebar menu -->
                <div class="navbar navbar-default" role="navigation">
                    <div class="container-fluid">

                        <!-- Page title -->
                        <ul class="nav navbar-nav list-inline navbar-left">
                            <li class="list-inline-item">
                                <button class="button-menu-mobile open-left">
                                    <i class="mdi mdi-menu"></i>
                                </button>
                            </li>
                            <li class="list-inline-item">
                                <h4 class="page-title">Starter</h4>
                            </li>
                        </ul>

                            <ul class="list-unstyled topbar-right-menu float-right mb-0">

                                <li>
                                    <!-- Notification -->
                                    <div class="notification-box">
                                        <ul class="list-inline mb-0">
                                            <li>
                                                <a href="javascript:void(0);" class="right-bar-toggle">
                                                    <i class="mdi mdi-bell-outline noti-icon"></i>
                                                </a>
                                                <div class="noti-dot">
                                                    <span class="dot"></span>
                                                    <span class="pulse"></span>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <!-- End Notification bar -->
                                </li>

                                <li class="hide-phone">
                                    <form class="app-search">
                                        <input type="text" placeholder="Search..."
                                               class="form-control">
                                        <button type="submit"><i class="fa fa-search"></i></button>
                                    </form>
                                </li>

                            </ul>
                        </nav>
                    </div><!-- end container -->
                </div><!-- end navbar -->
            </div>
            <!-- Top Bar End -->


            <!-- ========== Left Sidebar Start ========== -->
            <div class="left side-menu">
                <div class="sidebar-inner slimscrollleft">

                    <!-- User -->
                    <div class="user-box">
                        <?php include 'layouts/user-box.php' ?>
                    </div>
                    <!-- End User -->

                    <!--- Sidebar -->
                    <div id="sidebar-menu">
                        <?php include 'layouts/side.php' ?>
                        <div class="clearfix"></div>
                    </div>
                    <!-- Sidebar -->
                    <div class="clearfix"></div>

                </div>

            </div>
            <!-- Left Sidebar End -->



            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">


                        <div class="modal fade " tabindex="-1" role="dialog" id="modalLogout"
                             aria-labelledby="mySmallModalLabel"
                             aria-hidden="true" style="display: none;">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="text-center">Apakah Anda Yakin Ingin Keluar Dari Sistem?</h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <a href="<?= $this->url->get('keluar') ?>" class="btn btn-info btn-block">Ya,Keluar</a>
                                            </div>
                                            <div class="col-lg-6">
                                                <a href="<?= $this->url->get('') ?>" class="btn btn-default btn-block">Tidak</a>
                                            </div>
                                        </div>
                                    </div>
                                </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                        </div><!-- /.modal -->

                        <?= $this->getContent() ?>
                    </div> <!-- container -->

                </div> <!-- content -->

                <footer class="footer">
                    <?= date('Y') ?> © LPPM UIN SUSKA RIAU by. SZ
                </footer>

            </div>


            <!-- ============================================================== -->
            <!-- End Right content here -->
            <!-- ============================================================== -->


            <!-- /Right-bar -->

        </div>
        <!-- END wrapper -->

        <?php else: ?>

            <?= $this->getContent() ?>
        <?php endif; ?>

        <!-- jQuery  -->
        <script src="<?= $this->url->get("assets/js/jquery.min.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/popper.min.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/bootstrap.min.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/detect.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/fastclick.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/jquery.blockUI.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/waves.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/jquery.nicescroll.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/jquery.slimscroll.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/jquery.scrollTo.min.js")?>"></script>

        <!-- App js -->
        <script src="<?= $this->url->get("assets/js/jquery.core.js")?>"></script>
        <script src="<?= $this->url->get("assets/js/jquery.app.js")?>"></script>

    </body>
</html>