<?php
/**
 * Created by PhpStorm.
 * User: SarliZona
 * Date: 10/22/2018
 * Time: 22:29
 */
?>
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <div class="row">
                <div class="col-lg-12">
                    <form class="form-horizontal" method="post" action="" role="form">
                        <div class="form-group row">
                            <label class="col-md-2 control-label">Nama</label>
                            <div class="col-md-10">
                                <input type="text" placeholder="dosen/pegawai" class="form-control" name="nama" value="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 control-label" for="example-email">Email</label>
                            <div class="col-md-10">
                                <input type="email" id="example-email" name="email"
                                       class="form-control" placeholder="Email">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 control-label" >Nip / Nik</label>
                            <div class="col-md-10">
                                <input type="text" maxlength="20"
                                       name="nipnik"
                                       class="form-control" placeholder="Nip / Nik">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 control-label">password</label>
                            <div class="col-md-10">
                                <input type="password" maxlength="20"
                                       name="password"
                                       class="form-control" placeholder="password">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 control-label" >Hak Akses</label>
                            <div class="col-md-10">
                                <input type="text" maxlength="20"
                                       name="hakakses"
                                       class="form-control" placeholder="">
                            </div>
                        </div>
                        <button class="btn btn-primary btn-block" type="submit">Simpan</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

