<?php
/**
 * Created by PhpStorm.
 * User: SarliZona
 * Date: 10/19/2018
 * Time: 22:23
 */
?>

<?php
/**
 * Created by PhpStorm.
 * User: ahmadfauzirahman
 * Date: 02/06/18
 * Time: 5:11
 */
?>
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">

            <div class="dropdown pull-right">
                <a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown" aria-expanded="false">
                    <i class="zmdi zmdi-more-vert"></i>
                </a>
            </div>

            <!--            <h4 class="header-title m-t-0 m-b-30">U</h4>-->

            <div class="row">
                <div class="col-lg-12">
                    <form class="form-horizontal" action="" method="post" role="form">
                        <div class="form-group row">
                            <label class="col-md-2 control-label" for="example-email">Nip</label>
                            <div class="col-md-10">
                                <input type="text"  readonly value="<?= $pengguna->nip ?>"
                                       name="nip" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 control-label">Nama</label>
                            <div class="col-md-10">
                                <input type="text" name="nama" class="form-control" value="<?=
                                $pengguna->nama ?>">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-2 control-label" >Email</label>
                            <div class="col-md-10">
                                <input type="text" id="example-email" value="<?=
                                $pengguna->email ?>" name="email" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 control-label" >
                            Hak Akses</label>
                            <div class="col-md-10">
                                <input type="text" id="example-email" value="<?=
                                $pengguna->hak_akses ?>" name="hak_akses"
                                       class="form-control">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 control-label" >Password

                            </label>
                            <div class="col-md-10">
                                <input type="text"  value="<?=
                                $pengguna->password ?>" name="password" class="form-control">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 control-label" >Status Konfirmasi

                                </label>
                            <div class="col-md-10">
                                <input type="text" id="example-email" value="<?=
                                $pengguna->konfirmasi_email ?>" name="konfirmasi_email" class="form-control">
                            </div>
                        </div>
                        <button class="btn btn-primary btn-block">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


