<?php
/**
 * Created by PhpStorm.
 * User: jbenastey
 * Date: 08-Oct-18
 * Time: 21:36
 */
?>
<div class="row">
    <div class="col-12">
        <div class="card-box">
            <h4 class="m-t-0 header-title">Kwitansi</h4>


            <div class="row">
                <div class="col-12">
                    <div class="p-20">

                        <form action="" class="form-horizontal" role="form" name="add_name" id="add_name" method="post">
                            <div class="form-group row">
                                <label class="col-2 col-form-label">Nama</label>
                                <div class="col-10">
                                    <input type="text" class="form-control" placeholder="Nama" name="name">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-2 col-form-label">NIP</label>
                                <div class="col-10">
                                    <input type="text" class="form-control" placeholder="NIP" name="nip">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-2 col-form-label">Lokasi</label>
                                <div class="col-10">
                                    <input type="text" class="form-control" placeholder="Lokasi" name="location">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-2 col-form-label">Tanggal Berangkat</label>
                                <div class="col-4">
                                    <input type="date" class="form-control" name="datedepart">
                                </div>
                                <label class="col-2 col-form-label">Tanggal Pulang</label>
                                <div class="col-4">
                                    <input type="date" class="form-control" name="datereturn">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-2 col-form-label">Nomor SPB</label>
                                <div class="col-10">
                                    <input type="text" class="form-control" placeholder="Nomor SPB" name="nospb">
                                </div>
                            </div>


                            <div class="form-group row">
                                <label class="col-2 col-form-label">Rincian Biaya</label>
                                <div class="col-10">
                                    <table class="table table-bordered" id="dynamic_field">
                                        <tr>
                                            <td><label class="col-2">Deskripsi</label><input type="text" name="deskripsi[]" placeholder="Deskripsi" class="form-control name_list" /></td>
                                            <td><label class="col-2">Durasi</label><input type="text" name="durasi[]" placeholder="Durasi" class="form-control name_list" /></td>
                                            <td><label class="col-2">Biaya</label><input type="text" name="biaya[]" placeholder="Biaya" class="form-control name_list" /></td>
                                            <td><label class="col-2">Keterangan</label><input type="text" name="ket[]" placeholder="Keterangan" class="form-control name_list" /></td>

                                            <td><button type="button" name="add" id="add" class="btn btn-success">Add More</button></td>
                                        </tr>
                                    </table>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-2 col-form-label">Daftar Pengeluaran Riil</label>
                                <div class="col-10">
                                    <table class="table table-bordered" id="dynamic_field2">
                                        <tr>
                                            <td><label class="col-2">Deskripsi</label><input type="text" name="deskripsir[]" placeholder="Deskripsi" class="form-control name_list" /></td>
                                            <td><label class="col-2">Durasi</label><input type="text" name="durasir[]" placeholder="Durasi" class="form-control name_list" /></td>
                                            <td><label class="col-2">Biaya</label><input type="text" name="biayar[]" placeholder="Biaya" class="form-control name_list" /></td>

                                            <td><button type="button" name="add2" id="add2" class="btn btn-success">Add More</button></td>
                                        </tr>
                                    </table>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary">Simpan</button>

                        </form>
                    </div>
                </div>

            </div>
            <!-- end row -->

        </div> <!-- end card-box -->
    </div><!-- end col -->
</div>
<!-- end row -->

