<div class="row">
    <div class="col-12">
        <div class="card-box">
            <h4 class="m-t-0 header-title">Kwitansi</h4>
            <h2><?php $this->flashSession->output() ?></h2>

            <div class="row">
                <div class="col-12">
                    <div class="p-20">
                        <div class="panel-heading">
                            <a href="<?= $this->url->get('monitoring/receipt/add') ?>" class="btn btn-default btn-lg"><i
                                        class="fa fa-user-plus"></i> Tambah Kwitansi Baru</a>

                        </div>

                    </div>
                </div>

            </div>
            <!-- end row -->

        </div> <!-- end card-box -->
    </div><!-- end col -->
</div>
<!-- end row -->
