<?php

?>
<div class="row">

    <div class="col-lg-4 col-md-6">
        <div class="card-box">
            <h4 class="header-title m-t-0 m-b-30">Surat Izin Penelitian</h4>
            <div class="widget-chart-1">
                <div class="widget-chart-box-1">
                    <img src="<?= $this->url->get('img/toga.png') ?>" class="img-thumbnail" alt="">
                </div>

                <div class="widget-detail-1">
                    <h2 class="p-t-12"><?//= $pengajuan2 ?> Orang</h2>
                    <p class="text-muted"><a href="<?//= $this->url->get('tunggu-review') ?>"
                                             class="btn btn-primary btn-block"><i class="fa fa-desktop"></i>
                            Detail</a></p>
                </div>
            </div>
        </div>
    </div><!-- end col -->
    <div class="col-lg-4 col-md-6">
        <div class="card-box">
            <h4 class="header-title m-t-0 m-b-30">Surat Izin Pengabdian</h4>
            <div class="widget-chart-1">
                <div class="widget-chart-box-1">
                    <img src="<?= $this->url->get('img/toga.png') ?>" class="img-thumbnail" alt="">
                </div>

                <div class="widget-detail-1">
                    <h2 class="p-t-12"><?//=$pengajuan3 ?> Orang</h2>
                    <p class="text-muted"><a href="<?//= $this->url->get('proses-review') ?>"
                                             class="btn btn-warning btn-block"><i class="fa fa-desktop"></i>
                            Detail</a></p>
                </div>
            </div>
        </div>
    </div><!-- end col -->
    <div class="col-lg-4 col-md-6">
        <div class="card-box">
            <h4 class="header-title m-t-0 m-b-30">Surat Tugas Perjalanan Dinas</h4>
            <div class="widget-chart-1">
                <div class="widget-chart-box-1">
                    <img src="<?= $this->url->get('img/toga.png') ?>" class="img-thumbnail" alt="">
                </div>

                <div class="widget-detail-1">
                    <h2 class="p-t-12"><?//= $pengajuan4 ?> Orang</h2>
                    <p class="text-muted"><a href="<?//= $this->url->get('selesai-review') ?>"
                                             class="btn btn-danger btn-block"><i class="fa fa-desktop"></i>
                            Detail</a></p>
                </div>
            </div>
        </div>
    </div><!-- end col -->
	<div class="col-lg-4 col-md-6">
        <div class="card-box">
            <h4 class="header-title m-t-0 m-b-30">Surat FGD</h4>
            <div class="widget-chart-1">
                <div class="widget-chart-box-1">
                    <img src="<?= $this->url->get('img/toga.png') ?>" class="img-thumbnail" alt="">
                </div>

                <div class="widget-detail-1">
                    <h2 class="p-t-12"><?//= $pengajuan4 ?> Orang</h2>
                    <p class="text-muted"><a href="<?//= $this->url->get('selesai-review') ?>"
                                             class="btn btn-danger btn-block"><i class="fa fa-desktop"></i>
                            Detail</a></p>
                </div>
            </div>
        </div>
    </div><!-- end col -->
</div>