<?php
/**
 * Created by PhpStorm.
 * User: SarliZona
 * Date: 10/26/2018
 * Time: 22:42
 */
?>

<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <h4 class="header-title m-t-0 m-b-30"> Hallo : <?= $this->session->get('nama') ?></h4>
            <h4><?php $this->flashSession->output() ?></h4>

            <div class="row">
                <div class="col-lg-12">

                    <form class="form-horizontal" action="<?= $this->url->get('office/ganti/'. $this->session->get('nip') )?>" method="post" role="form"
                          enctype="multipart/form-data">
                        <div class="form-group row">
                            <label class="col-md-2 control-label">Password Lama</label>
                            <div class="col-md-10">
                                <?= $form->render('password'),
                                $form->messages('password') ?>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-md-2 control-label">Password Baru</label>
                            <div class="col-md-10">
                                <?= $form->render('passwordbaru'),
                                $form->messages('passwordbaru') ?>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-2 control-label">Ulangi Password Baru</label>
                            <div class="col-md-10">
                                <?= $form->render('confirmPasswordbaru'),
                                $form->messages('confirmPasswordbaru') ?>
                            </div>
                        </div>


                        <div class="form-group text-center m-t-40">
                            <div class="col-xs-12">
                                <button class="btn btn-custom btn-bordred btn-block waves-effect waves-light" type="submit">
                                    Ganti
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

