<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <link rel="shortcut icon" href="<?= $this->url->get('assets/images/favicon.ico') ?>">


    <title>Office Automation | <?= $halaman ?></title>

    <!-- Sweet Alert css -->
    <link href="<?= $this->url->get('assets/plugins/sweet-alert/sweetalert2.min.css') ?>" rel="stylesheet"
          type="text/css"/>

    <!-- DataTables -->
    <link href="<?= $this->url->get('assets/plugins/datatables/dataTables.bootstrap4.min.css') ?>" rel="stylesheet"
          type="text/css"/>
    <link href="<?= $this->url->get('assets/plugins/datatables/buttons.bootstrap4.min.css') ?>" rel="stylesheet"
          type="text/css"/>
    <!-- Responsive datatable examples -->
    <link href="<?= $this->url->get('assets/plugins/datatables/responsive.bootstrap4.min.css') ?>" rel="stylesheet"
          type="text/css"/>
    <!-- Multi Item Selection examples -->
    <link href="<?= $this->url->get('assets/plugins/datatables/select.bootstrap4.min.css') ?>" rel="stylesheet"
          type="text/css"/>

    <!-- Table Responsive css -->
    <link href="<?= $this->url->get('assets/plugins/responsive-table/css/rwd-table.min.css') ?>" rel="stylesheet"
          type="text/css" media="screen">



    <!-- App css -->
    <link href="<?= $this->url->get('assets/css/bootstrap.min.css') ?>" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->get('assets/css/icons.css') ?>" rel="stylesheet" type="text/css"/>
    <link href="<?= $this->url->get('assets/css/style.css') ?>" rel="stylesheet" type="text/css"/>

    <link href="<?= $this->url->get('assets/plugins/fileuploads/css/dropify.min.css') ?>" rel="stylesheet"
          type="text/css"/>
    <!-- Plugins css-->
    <link href="<?= $this->url->get('assets/plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.css') ?>"
          rel="stylesheet"/>
    <link href="<?= $this->url->get('assets/plugins/multiselect/css/multi-select.css') ?>" rel="stylesheet"
          type="text/css"/>

    <link href="<?= $this->url->get('assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css') ?>"
          rel="stylesheet"/>
    <link href="<?= $this->url->get('assets/plugins/switchery/switchery.min.css') ?>" rel="stylesheet"/>
    <link href="<?= $this->url->get('assets/plugins/timepicker/bootstrap-timepicker.min.css') ?>" rel="stylesheet">
    <link href="<?= $this->url->get('assets/plugins/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css') ?>"
          rel="stylesheet">
    <link href="<?= $this->url->get('assets/plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') ?>"
          rel="stylesheet">
    <link href="<?= $this->url->get('assets/plugins/bootstrap-daterangepicker/daterangepicker.css') ?>"
          rel="stylesheet">

    <link href="<?= $this->url->get('assets/plugins/select2/css/select2.min.css') ?>" rel="stylesheet" type="text/css" />




    <script src="<?= $this->url->get('assets/js/modernizr.min.js') ?>"></script>

    <link href="<?= $this->url->getStatic('AdminTo/css/icons.css') ?>" rel="stylesheet" type="text/css"/>


</head>

<?php if ($this->session->get('nip')): ?>

<body class="fixed-left">

<!-- Begin page -->
<div id="wrapper">

    <!-- Top Bar Start -->
    <div class="topbar">

        <!-- LOGO -->
        <div class="topbar-left">
            <a href="index.html" class="logo"><span>Office<span> To</span></span><i class="mdi mdi-layers"></i></a>
        </div>

        <!-- Button mobile view to collapse sidebar menu -->
        <div class="navbar navbar-default" role="navigation">
            <div class="container-fluid">

                <!-- Page title -->
                <ul class="nav navbar-nav list-inline navbar-left">
                    <li class="list-inline-item">
                        <button class="button-menu-mobile open-left">
                            <i class="mdi mdi-menu"></i>
                        </button>
                    </li>
                    <li class="list-inline-item">
                        <h4 class="page-title"><?= $halaman ?></h4>
                    </li>
                </ul>

                <ul class="list-unstyled topbar-right-menu float-right mb-0">

                    <li>
                        <!-- Notification -->
                        <div class="notification-box">
                            <ul class="list-inline mb-0">
                                <li>
                                    <a href="javascript:void(0);" class="right-bar-toggle">
                                        <i class="mdi mdi-bell-outline noti-icon"></i>
                                    </a>
                                    <div class="noti-dot">
                                        <span class="dot"></span>
                                        <span class="pulse"></span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <!-- End Notification bar -->
                    </li>

                    <li class="hide-phone">
                        <form class="app-search">
                            <input type="text" placeholder="Search..."
                                   class="form-control">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </li>

                </ul>
                </nav>
            </div><!-- end container -->
        </div><!-- end navbar -->
    </div>
    <!-- Top Bar End -->


    <!-- ========== Left Sidebar Start ========== -->
    <div class="left side-menu">
        <div class="sidebar-inner slimscrollleft">

            <!-- User -->
            <div class="user-box">
                <?php include 'layouts/user-box.php' ?>

            </div>
            <!-- End User -->

            <!--- Sidemenu -->
            <div id="sidebar-menu">
                <?php include 'layouts/side.php' ?>
                <div class="clearfix"></div>
            </div>

            <!-- Sidebar -->
            <div class="clearfix"></div>

        </div>
    </div>
    <!-- Left Sidebar End -->


    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container-fluid">

                <!--                        //modal logout-->
                <div class="modal fade " tabindex="-1" role="dialog" id="modalLogout"
                     aria-labelledby="mySmallModalLabel"
                     aria-hidden="true" style="display: none;">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="text-center">Apakah Anda Yakin Ingin Keluar Dari Sistem?</h4>
                            </div>
                            <div class="modal-body">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <a href="<?= $this->url->get('office/keluar') ?>"
                                           class="btn btn-info btn-block">Ya,Keluar</a>
                                    </div>
                                    <div class="col-lg-6">
                                        <a data-dismiss="modal"
                                           class="btn btn-inverse btn-trans btn-block waves-effect w-md waves-inverse m-b-10">Tidak</a>
                                    </div>
                                </div>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

                <?= $this->getContent() ?>
            </div> <!-- container -->

        </div> <!-- content -->

        <footer class="footer">
            <?= date('Y') ?> © LPPM UIN SUSKA RIAU by SZ

        </footer>

    </div>


    <!-- ============================================================== -->
    <!-- End Right content here -->
    <!-- ============================================================== -->


    <!-- /Right-bar -->

</div>
<!-- END wrapper -->

<?php else: ?>

    <?= $this->getContent() ?>
<?php endif; ?>

<!-- jQuery  -->
<script src="<?= $this->url->get("assets/js/jquery.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/js/popper.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/js/bootstrap.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/js/detect.js") ?>"></script>
<script src="<?= $this->url->get("assets/js/fastclick.js") ?>"></script>
<script src="<?= $this->url->get("assets/js/jquery.blockUI.js") ?>"></script>
<script src="<?= $this->url->get("assets/js/waves.js") ?>"></script>
<script src="<?= $this->url->get("assets/js/jquery.nicescroll.js") ?>"></script>
<script src="<?= $this->url->get("assets/js/jquery.slimscroll.js") ?>"></script>
<script src="<?= $this->url->get("assets/js/jquery.scrollTo.min.js") ?>"></script>


<!-- Required datatable js -->
<script src="<?= $this->url->get("assets/plugins/datatables/jquery.dataTables.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/plugins/datatables/dataTables.bootstrap4.min.js") ?>"></script>
<!-- Buttons examples -->
<script src="<?= $this->url->get("assets/plugins/datatables/dataTables.buttons.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/plugins/datatables/buttons.bootstrap4.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/plugins/datatables/jszip.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/plugins/datatables/pdfmake.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/plugins/datatables/vfs_fonts.js") ?>"></script>
<script src="<?= $this->url->get("assets/plugins/datatables/buttons.html5.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/plugins/datatables/buttons.print.min.js") ?>"></script>

<!-- Key Tables -->
<script src="<?= $this->url->get("assets/plugins/datatables/dataTables.keyTable.min.js") ?>"></script>

<!-- Responsive examples -->
<script src="<?= $this->url->get("assets/plugins/datatables/dataTables.responsive.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/plugins/datatables/responsive.bootstrap4.min.js") ?>"></script>

<!-- Selection table -->
<script src="<?= $this->url->get("assets/plugins/datatables/dataTables.select.min.js") ?>"></script>


<!-- App js -->
<script src="<?= $this->url->get("assets/js/jquery.core.js") ?>"></script>
<script src="<?= $this->url->get("assets/js/jquery.app.js") ?>"></script>

<!-- file uploads js -->
<script src="<?= $this->url->get("assets/plugins/fileuploads/js/dropify.min.js") ?>"></script>



<!-- responsive-table-->
<script src="<?= $this->url->get("assets/plugins/responsive-table/js/rwd-table.min.js") ?>"
        type="text/javascript"></script>

<!-- Validation js (Parsleyjs) -->
<script type="text/javascript" src="<?= $this->url->get("assets/plugins/parsleyjs/dist/parsley.min.js") ?>"></script>

<!--Select2 -->
<script type="text/javascript" src="<?= $this->url->get('assets/plugins/jquery-quicksearch/jquery.quicksearch.js') ?>"></script>
<script src="<?= $this->url->get('assets/plugins/select2/js/select2.min.js') ?>" type="text/javascript"></script>



<!-- daterange-->
<script src="<?= $this->url->get("assets/plugins/moment/moment.js") ?>"></script>
<script src="<?= $this->url->get("assets/plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/plugins/bootstrap-daterangepicker/daterangepicker.js") ?>"></script>
<script src="<?= $this->url->get("assets/plugins/timepicker/bootstrap-timepicker.min.js") ?>"></script>

<!-- Sweet Alert Js  -->
<script src="<?= $this->url->get("assets/plugins/sweet-alert/sweetalert2.min.js") ?>"></script>
<script src="<?= $this->url->get("assets/pages/jquery.sweet-alert.init.js") ?>"></script>


<script src="<?= $this->url->get("assets/js/lppm.js") ?>"></script>





<script type="text/javascript">
    $('.dropify').dropify({
        messages: {
            'default': 'Drag and drop a file here or click',
            'replace': 'Drag and drop or click to replace',
            'remove': 'Remove',
            'error': 'Ooops, something wrong appended.'
        },
        error: {
            'fileSize': 'The file size is too big (1M max).'
        }
    });

    jQuery('#datepicker').datepicker();
    jQuery('#datepicker-autoclose').datepicker({
        autoclose: true,
        todayHighlight: true
    });
    jQuery('#datepicker-inline').datepicker();
    jQuery('#datepicker-multiple-date').datepicker({
        format: "mm/dd/yyyy",
        clearBtn: true,
        multidate: true,
        multidateSeparator: ","
    });
    jQuery('#date-range').datepicker({
        toggleActive: true
    });

</script>

<?php include 'izin_pengabdian/_addDinamis.php' ?>
<?php include 'tugas_perjalanan/_addDinamis.php' ?>
<?php include 'fgd/_addDinamis.php' ?>
<?php include 'izin_penelitian/_addDinamis.php' ?>

</body>
</html>